FRAMEWORK_PATH="${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME}"
# FRAMEWORK_PATH="hello"
echo $FRAMEWORK_PATH
cp -r $FRAMEWORK_PATH "${PROJECT_DIR}/../${PROJECT}Demo/"
cp -r "${FRAMEWORK_PATH}/${PROJECT}.bundle" "${PROJECT_DIR}/../${PROJECT}Demo/"